controller_manager:
  ros__parameters:
    update_rate: 50  # Aktualisierungsrate des Controller-Managers in Hz
    use_sim_time: true
    tricycle_controller:
      type: tricycle_controller/TricycleController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
joint_state_broadcaster:
  ros__parameters:
    extra_joints: ["right_wheel_joint", "left_wheel_joint"]
    publish_rate: 50.0
tricycle_controller:
  ros__parameters:
    # Model
    use_sim_time: true
    publish_rate: 50.0
    traction_joint_name: "front_wheel_joint"  # Name des Antriebs-Joints
    steering_joint_name: "front_steering_joint"  # Name des Lenkungs-Joints
    wheelbase: 0.65    # Abstand zwischen Vorder- und Hinterachse in Metern
    wheel_radius: 0.0625  # Radius des Antriebsrads in Metern
    #Odometry
    odom_frame_id: odom
    base_frame_id: base_link
    open_loop: false # If True, uses cmd_vel instead of hardware interface
    enable_odom_tf: true # If True, publishes odom<-base_link TF
    odom_only_twist: false # If True, publishes on /odom only
    pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    velocity_rolling_window_size: 10 # Rolling window size of rcppmath
    # Rate Limiting
    traction: # All values should be positive
      min_velocity: 0.0
      max_velocity: 0.5
      # min_acceleration: 0.0
      max_acceleration: 5.0
      # min_deceleration: 0.0
      max_deceleration: 8.0
      # min_jerk: 0.0
      # max_jerk: 1000.0
    steering:
      min_position: -1.57
      max_position: 1.57
      # min_velocity: 0.0
      max_velocity: 1.0
      # min_acceleration: 0.0
      # max_acceleration: 1000.0
    cmd_vel_timeout: 500  # Timeout in Millisekunden
    use_stamped_vel: false
    publish_ackermann_command: false # Publishes AckermannDrive.
